sudo: required

language: go

go_import_path: github.com/bosh-prometheus/firehose_exporter

services:
  - docker

jobs:
  include:
    - stage: Run tests
      script: make test

    - stage: Build docker image
      env:
        - DOCKER_IMAGE_NAME=boshprometheus/firehose-exporter
        - secure: lB3bIMLhPSBOnYJTWZJtMZPgFVNL+7ms/oMERMu9alCYACjLUlN6ElEbMNRMNWR100n0/Eilf1fiZnkn6cKENAx1HIk8sWDGkWIes8Ie91bAr0DTYXnTo28FhQzKjjKnOhUcc9+cfU1w09jKdgi8+mTUy5PMNdW41HeU5LQpuuOHpF4rnRNsFN4RTjFSQXpcghO7rmdW4VZZ28Pb9mU43Sblma32PLVkiJk+f2dFE4cInsp04X+kN64Z3kFPZSfUv52J0JJgWXPQrxDkahJayzo1rdKrXjdFUOKJ+xHL3j94aVGJTqeGt4RbEClr950EZsqbrU+oG6jCTU0qSg3ofcvqiMfogSllqnvGo2uQN1Ahf9rRQUyEfKO34VyLy8lQYSO9lE2abU7BkTpSpAeqgOL/tVJPMTNGJpDQeEgf0Hb3EV7tEz2hgf1CNEu9tmR8ZTsDaKNuw8fhOVIQzFnOGika5H4mLYOAg2s2f31j4hwYdZSURkFo1XWswcDjyw4m7mvN7UL1qzAkMinkkhBMEPU90e319Mt8lc5roFzbR6gO16MDiWdIy1UOAM55lVklP7fdorJX3HOESUxIoYSenVGvjvugEc+OL7NdVgf9XFJQgy1AdYcFTPFGaB6+hKJpNkWfQeYMi0wducjCHr9+XF9NarumdHIGDbuLPd/2HhY=
        - secure: F0VmLi4ibpX6T+jgCzjwE6wbozC2FGQG4I14560yRuie2LtCh2QRsfCIzg7DkXnBT+ENqGPlihOgUqOFSnWz7v2KE0/ETik67xoiIfTjs2jAGgx12VsFlbjXTWDHCtBrRqHGiygtS64XdCm28iC8/yqILEYdiLC0mlrxkLQG4ysZm/i7cJCn1nTovGZnslI7+n77cOiBBgAlxZ0omOQcX3OEGdgno+Q8D1M836JusxW+c/iQZEple66tyOFnG3AQ5Eor6Uii3ywcRoUoF0C5eNWzsq7Qpac5iAn/0Z0CItiTvxvCMEV/rhdQibd8kqbJTUv2YwSbMT22eXBH+UXqauBf06Bg1eQuBMXMM4wUpEErjEHvRg0hIzm6SzxvPDUd9VYfh0ChOIFmOaQ8RDz9c2VoAwm4ku8rQIX94aphUY+LZjmWtw/FiH18z4fma9/uNL3Iavcp9RrOK/YbXRFODy2bxGh9ARJTQbE9Fzk6WmU4JJ1q+HO7u0kJJOe+i0VokBH3Jv6+3ccySng00/KwOuwQxETXJyYwrG4bBIpgKCCw/svcCaDaoz38JwptKvX1rqvi43Cos6e76ZiHeScf46PFqnZFHzC8/mbkyOoqejbwtFEiuK+DVCtO/+4WaVdti/VhIAescM+xf+vnSWWk1rcR5GDErbqtoEgPeUInknM=
      script:
        - make crossbuild
        - ln -s .build/linux-amd64/firehose_exporter firehose_exporter
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
